FROM lukemathwalker/cargo-chef:latest-rust-1.81 AS chef
WORKDIR /app

FROM chef AS planner
COPY . .
RUN cargo chef prepare --recipe-path recipe.json

FROM chef AS builder 
COPY --from=planner /app/recipe.json recipe.json
# Build dependencies - this is the caching layer!
RUN cargo chef cook --release --recipe-path recipe.json
# Build application
COPY . .
RUN cargo build --release --bin riemann-solver

FROM debian:bookworm-slim AS runtime
WORKDIR /app
COPY --from=builder /app/target/release/riemann-solver /usr/local/bin
ENTRYPOINT ["/usr/local/bin/riemann-solver"]
